Refactor the kara-x puavo-pkg package.

diff --git a/kara-x/rules b/kara-x/rules
--- a/kara-x/rules
+++ b/kara-x/rules
@@ -5,50 +5,33 @@ set -eu
 command=$1
 shift
 
-links='
-  javascriptkara-x.jar
-  kara-x.jar
-  multikara-x.jar
-  pythonkara-x.jar
-  rubykara-x.jar
-  turingkara-x.jar
-'
-
-case "$command" in
-  configure)
-    upstream_dir=$1
-    mkdir -p /opt/kara-x
-    for f in $links; do
-      mkdir -p "$(dirname "$f")"
-      ln -fns -T "${upstream_dir}"/"${f}" /opt/kara-x/"$f"
-    done
-
-    desktops=$(cat <<'EOF'
+spec_list='
 javascriptkara-x.jar|JavaScriptKara X|javascriptkara-x
 kara-x.jar|Kara X|kara-x
 multikara-x.jar|MultiKara X|multikara-x
 pythonkara-x.jar|PythonKara X|pythonkara-x
 rubykara-x.jar|RubyKara X|rubykara-x
 turingkara-x.jar|TuringKara X|turingkara-x
-EOF
-)
+'
 
-    printf '%s\n' "$desktops" | while IFS= read -r SPEC; do
-      [ -n "$SPEC" ] || continue
-      OIFS=$IFS
-      IFS='|'
-      set -- $SPEC
-      IFS=$OIFS
-      JAR="$1"
-      DNAME="$2"
-      DID="$3"
-      [ -n "$JAR" ] && [ -n "$DNAME" ] && [ -n "$DID" ] || continue
+case "$command" in
+  configure)
+    upstream_dir=$1
+    mkdir -p /opt/kara-x
+    printf %s "$spec_list" | while IFS= read -r spec; do
+      test -n "$spec" || continue
+      jar=$(         printf %s "$spec" | cut -d '|' -f 1)
+      name=$(        printf %s "$spec" | cut -d '|' -f 2)
+      desktop_name=$(printf %s "$spec" | cut -d '|' -f 3)
 
-      cat > "/usr/share/applications/$DID.desktop" <<EOF
+      mkdir -p "$(dirname "$jar")"
+      ln -fns -T "${upstream_dir}/${jar}" "/opt/kara-x/${jar}"
+
+      cat > "/usr/share/applications/${desktop_name}.desktop" <<EOF
 [Desktop Entry]
 Type=Application
-Name=$DNAME
-Exec=java -jar /opt/kara-x/$JAR
+Name=${name}
+Exec=java -jar /opt/kara-x/${jar}
 Icon=application-x-addon
 Terminal=false
 Categories=Education;
@@ -58,19 +41,19 @@ EOF
     ;;
 
   unconfigure)
-    rm -rf /opt/kara-x
-    rm -f /usr/share/applications/javascriptkara-x.desktop \
-          /usr/share/applications/kara-x.desktop           \
-          /usr/share/applications/multikara-x.desktop      \
-          /usr/share/applications/pythonkara-x.desktop     \
-          /usr/share/applications/rubykara-x.desktop       \
-          /usr/share/applications/turingkara-x.desktop
+    printf %s "$spec_list" | while IFS= read -r spec; do
+      test -n "$spec" || continue
+      jar=$(         printf %s "$spec" | cut -d '|' -f 1)
+      desktop_name=$(printf %s "$spec" | cut -d '|' -f 3)
+      rm -f "/opt/kara-x/${jar}" \
+             /usr/share/applications/${desktop_name}.desktop
+    done
+    rmdir --ignore-fail-on-non-empty /opt/kara-x
     ;;
 
   unpack)
     upstream_pack=$1
     upstream_dir=$2
-
     tar -x -f "$upstream_pack" -C "$upstream_dir"
     ;;
 
@@ -86,14 +69,14 @@ EOF
       while read sha384 fwfilepath; do
         fwfile=$(basename "$fwfilepath")
         wget --no-use-server-timestamps --no-cookies \
-          --output-document "$fwfile" --progress=dot:mega \
-          "$fwfilepath" || {
-            [ $? -eq 4 ] && exit 2 ## Network failure.
-            exit 1
-        }
+             --output-document "$fwfile" --progress=dot:mega \
+             "$fwfilepath" || {
+               [ $? -eq 4 ] && exit 2 ## Network failure.
+               exit 1
+             }
         if ! echo "${sha384} $(basename $fwfilepath)" | sha384sum --check >/dev/null; then
           actual_checksum=$(sha384sum "$fwfile" | awk '{ print $1 }')
-          echo "checksum NOT matching for $fwfilepath" >&2
+          echo "checksum NOT matching for ${fwfilepath}" >&2
           echo "expected: ${sha384} / actual: ${actual_checksum}" >&2
           exit 1
         fi
