Make puavo-firmware work (better) & future-proof.

diff --git a/puavo-firmware/rules b/puavo-firmware/rules
--- a/puavo-firmware/rules
+++ b/puavo-firmware/rules
@@ -5,21 +5,65 @@ set -eu
 command=$1
 shift
 
+
+urlbase='https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/'
+
+
 case "${command}" in
     configure)
 	upstream_dir=$1
+	ln -fns "${upstream_dir}/iwlwifi-so-a0-gf-a0-71.ucode" /lib/firmware/iwlwifi-so-a0-gf-a0-71.ucode
 	ln -fns "${upstream_dir}/iwlwifi-so-a0-gf-a0.pnvm" /lib/firmware/iwlwifi-so-a0-gf-a0.pnvm
 	;;
     unconfigure)
         rm -rf /lib/firmware/iwlwifi-so-a0-gf-a0.pnvm
+        rm -rf /lib/firmware/iwlwifi-so-a0-gf-a0-71.ucode
 	;;
     unpack)
 	upstream_pack=$1
 	upstream_dir=$2
 
-	mkdir -p "${upstream_dir}"
-        cp "${upstream_pack}" "${upstream_dir}/iwlwifi-so-a0-gf-a0.pnvm"
+    tar -x -f "$upstream_pack" -C "$upstream_dir"
 	;;
+
+	download) #based on ubuntu-wallpapers-bullseye
+    upstream_pack=$(readlink -f "$1")
+    tmpdir=
+    trap '[ -n "$tmpdir" ] && rm -rf "$tmpdir"' 0 INT TERM
+    tmpdir=$(mktemp -d)
+
+    (
+      cd "$tmpdir"
+      mkdir -p puavo-firmware
+      while read sha384 fwfilepath; do
+        fwfile=$(basename "$fwfilepath")
+        wget \
+            --no-use-server-timestamps \
+            --no-cookies \
+            --output-document "$fwfile" \
+            --progress=dot:mega \
+            "${urlbase}/${fwfilepath}" || {
+            [ $? -eq 4 ] && exit 2 ## Network failure.
+            exit 1
+        }
+        if ! echo "${sha384} ${fwfilepath}" | sha384sum --check >/dev/null; then
+          actual_checksum=$(sha384sum "$debfile" | awk '{ print $1 }')
+          echo "checksum NOT matching for $fwfilepath" >&2
+          echo "expected: ${sha384} / actual: ${actual_checksum}" >&2
+          exit 1
+        fi
+        mv "$fwfile" puavo-firmware/ || exit 1
+      done <<EOF
+47c7e527f85c38c3c17ebd0ca5531f29da8509f1a87f9b39a9c6de7c565cf2dfa351e81390cc8c2e3a4796c8b9406ff1  iwlwifi-so-a0-gf-a0.pnvm
+b1e31efc3506cb20ca9c27c33c66cb6f063a7ef7d8f8c8f1bf8a9c0b05cba658d0767f5b89c8ffec92dfb10b90b24305  iwlwifi-so-a0-gf-a0-71.ucode
+EOF
+      # Set LC_COLLATE=C so that files always sort in the same
+      # way (so we get the same tar-archive independent of locales).
+      env LC_COLLATE=C \
+        tar -C puavo-firmware --mtime='2000-01-01 00:00:00 +00:00' --sort=name -c \
+          -f "$upstream_pack" .
+    )
+    ;;
     *)
 	;;
 esac
